
"""
Don't make fully vertical rails, they will break the program.
"""

TRACK_NAME = "Nyugati Railway Station"

POINTS = {
    'SA' : (0, 5, "left"),
    'BA' : (40, 5, "right"),
    'AB1': (50, 5),
    'EA' : (97, 5, "right left"),
    'ZA' : (300, 5, "right auto"),
    'TB' : (-200, 15, "left auto"),
    'SB' : (3, 15, "left"),
    'BB' : (40, 15, "right"),
    'BC1': (65, 15),
    'AB2': (70, 15),
    'EB' : (97, 15, "right left"),
    'ZB' : (300, 15, "right auto"),
    "SC" : (0, 30,  "left"),
    "BC" : (40, 30, "right"),
    "EC" : (70, 30),
    "BC2": (45, 30),
    "TD" : (-200, 45, "left auto"),
    "SD" : (3, 45, "left"),
    "BD" : (40, 45, "right"),
    "DE1": (55, 60),
    "DE4": (90, 60),
    "ED" : (97, 60, "right left"),
    "ZD" : (300, 60, "right auto"),
    "SE" : (0, 60, "left"),
    "BE" : (40, 60, "right"),
    "E2" : (55, 70),
    "DE2": (65, 70),
    "EG1": (70, 70),
    "DE3": (75, 70),
    "EE" : (97, 70, "right left"),
    "ZE" : (300, 70, "right auto"),
    "TF" : (-200, 70, "left auto"),
    "SF" : (3, 70, "left"),
    "BF" : (40, 70, "right"),
    "F2" : (75, 40),
    "CF" : (90, 40),
    "EF" : (97, 40, "right left"),
    "ZF" : (300, 40, "right auto"),
    "SG" : (0, 85, "left"),
    "BG" : (40, 85, "right"),
    "EG2": (75, 85),
    "EG" : (80, 85),
    "TH" : (-200, 95, "left auto"),
    "SH" : (3, 95, "left"),
    "BH" : (40, 95, "right"),
    "GH" : (95, 95),
    "EH" : (97, 95, "right left"),
    "ZH" : (300, 95, "right auto"),
    }

RAILS = {
    "A1" : ("SA", "BA", None, "A2"),
    "A2" : ("BA", "AB1", "A1", "A3"),
    "A3" : ("AB1", "EA", "A2", "ZA"),
    "ZA" : ("EA", "ZA", "A3", None, False),

    "TB" : ("TB", "SB", None, "B1", True),
    "B1" : ("SB", "BB", "TB", "B2", True),
    "B2" : ("BB", "BC1", "B1", "B3"),
    "B3" : ("BC1", "AB2", "B2", "B4"),
    "B4" : ("AB2", "EB", "B3", "ZB"),
    "ZB" : ("EB", "ZB", "B4", None, False),

    "C1" : ("SC", "BC", None, "C2"),
    "C2" : ("BC", "BC2", "C1", "C3"),
    "C3" : ("BC2", "EC", "C2", "C4"),
    "C4" : ("EC", "CF", "C3", None, False, 80),
    
    "TD" : ("TD", "SD", None, "D1", True),
    "D1" : ("SD", "BD", "TD", "D2", True),
    "D2" : ("BD", "DE1", "D1", "D3"),
    "D3" : ("DE1", "DE4", "D2", "D4"),
    "D4" : ("DE4", "ED", "D3", "ZD"),
    "ZD" : ("ED", "ZD", "D4", None, False),

    "E1" : ("SE", "BE", None, "E2"),
    "E2" : ("BE", "E2", "E1", "E3"),
    "E3" : ("E2", "DE2", "E2", "E4"),
    "E4" : ("DE2", "EG1", "E3", "E5"),
    "E5" : ("EG1", "DE3", "E4", "E6"),
    "E6" : ("DE3", "EE", "E5", "ZE"),
    "ZE" : ("EE", "ZE", "E6", None, False),
    
    "TF" : ("TF", "SF", None, "F1", True),
    "F1" : ("SF", "BF", "TF", "F2", True),
    "F2" : ("BF", "F2", "F1", "F3", True),
    "F3" : ("F2", "CF", "F2", "F4"),
    "F4" : ("CF", "EF", "F3", "ZF"),
    "ZF" : ("EF", "ZF", "F4", None, False),

    "G1" : ("SG", "BG", None, "G2"),
    "G2" : ("BG", "EG2", "G1", "G3"),
    "G3" : ("EG2", "EG", "G2", "G4"),
    "G4" : ("EG", "GH", "G3", None, False, 80),

    "TH" : ("TH", "SH", None, "H1", True),
    "H1" : ("SH", "BH", "TH", "H2", True),
    "H2" : ("BH", "GH", "H1", "H3"),
    "H3" : ("GH", "EH", "H2", "ZH"),
    "ZH" : ("EH", "ZH", "H3", None, False),
        

    "AB" : ("AB1", "AB2", None, None, False, 80),
    "BC" : ("BC2", "BC1", None, None, False, 80),
    "DE1" : ("DE1", "DE2", None, None, False, 80),
    "DE2" : ("DE3", "DE4", None, None, False, 80),
    "EG" : ("EG1", "EG2", None, None, False, 40),
}

SWITCHES = {
    "AB1" : ("A2", "A3", "AB"),
    "AB2" : ("B4", "B3", "AB"),
    "BC1" : ("B3", "B2", "BC"),
    "BC2" : ("C2", "C3", "BC"),
    "CF" : ("F4", "F3", "C4"),
    "DE1" : ("D2", "D3", "DE1"),
    "DE2" : ("E4", "E3", "DE1"),
    "DE3" : ("E5", "E6", "DE2"),
    "DE4" : ("D4", "D3", "DE2"),
    "EG1" : ("E4", "E5", "EG"),
    "EG2" : ("G3", "G2", "EG"),
    "GH" : ("H3", "H2", "G4"),
    }
